(prelude-require-package 'powerline)
(prelude-require-package 'flymake-cursor)
(prelude-require-package 'jedi)
(prelude-require-package 'python-cell)
(prelude-require-package 'neotree)
(prelude-require-package 'rust-mode)
(prelude-require-package 'company-irony)
(prelude-require-package 'cpputils-cmake)
(prelude-require-package 'grizzl)
(prelude-require-package 'google-c-style)
(prelude-require-package 'rust-mode)

(require 'rust-mode)
(require 'google-c-style)
(require 'cpputils-cmake)
(require 'company-irony)
(require 'rust-mode)
(require 'neotree)
(require 'python)
(require 'python-cell)
(require 'grizzl)
(require 'yasnippet)
(require 'key-chord)

(require 'powerline)
(require 'jedi)
(require 'flymake-cursor)
(require 'auto-complete)
(require 'auto-complete-config)

; (ac-config-default)
;;; end
